### ISSUE TITLE
[vite:css] start value has mixed support, consider using flex-start instead 

### ISSUE THREAD

**Issue by a-luna** [leveluptuts/svelte-toy#3]
This warning message appears in the console after adding an instance of `Toy.svelte` to my project:

```shell
[vite:css] start value has mixed support, consider using flex-start instead
```

The CSS that is causing this warning is line 92 in the `style` block of `Row.svelte`:

```css
	.st-container {
		display: flex;
		align-items: baseline;
		justify-content: start;
		margin-bottom: 2px;
	}
```

Changing `justify-content: start` to `justify-content: flex-start` removes the warning message.
